package view;

public class LightsOnView extends javax.swing.JFrame {

    public LightsOnView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jBtnGame0 = new javax.swing.JButton();
        jBtnGame1 = new javax.swing.JButton();
        jBtnGame2 = new javax.swing.JButton();
        jBtnGame3 = new javax.swing.JButton();
        jBtnGame4 = new javax.swing.JButton();
        jBtnGame5 = new javax.swing.JButton();
        jBtnGame6 = new javax.swing.JButton();
        jBtnGame7 = new javax.swing.JButton();
        jBtnGame8 = new javax.swing.JButton();
        jBtnUjra = new javax.swing.JButton();
        jLblFelkapcs = new javax.swing.JLabel();
        jTxtFelkapcsLampa = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuBar = new javax.swing.JMenu();
        jMnuItemJatekSzabaly = new javax.swing.JMenuItem();
        jMnuItemKilepes = new javax.swing.JMenuItem();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LightsOn");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 15, 15));

        jBtnGame0.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame0);

        jBtnGame1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame1);

        jBtnGame2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame2);

        jBtnGame3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame3);

        jBtnGame4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.add(jBtnGame4);

        jBtnGame5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame5);

        jBtnGame6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame6);

        jBtnGame7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame7);

        jBtnGame8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jBtnGame8);

        jBtnUjra.setText("Újraindítás");

        jLblFelkapcs.setText("Felkapcsolt lámpák:");

        jTxtFelkapcsLampa.setEditable(false);
        jTxtFelkapcsLampa.setText("1");

        jMnuBar.setText("Menü");

        jMnuItemJatekSzabaly.setText("Játékszabályzat...");
        jMnuBar.add(jMnuItemJatekSzabaly);

        jMnuItemKilepes.setText("Kilépés");
        jMnuBar.add(jMnuItemKilepes);

        jMenuBar1.add(jMnuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblFelkapcs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFelkapcsLampa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUjra)
                    .addComponent(jLblFelkapcs)
                    .addComponent(jTxtFelkapcsLampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LightsOnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LightsOnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LightsOnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LightsOnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LightsOnView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGame0;
    private javax.swing.JButton jBtnGame1;
    private javax.swing.JButton jBtnGame2;
    private javax.swing.JButton jBtnGame3;
    private javax.swing.JButton jBtnGame4;
    private javax.swing.JButton jBtnGame5;
    private javax.swing.JButton jBtnGame6;
    private javax.swing.JButton jBtnGame7;
    private javax.swing.JButton jBtnGame8;
    private javax.swing.JButton jBtnUjra;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLblFelkapcs;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuBar;
    private javax.swing.JMenuItem jMnuItemJatekSzabaly;
    private javax.swing.JMenuItem jMnuItemKilepes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtFelkapcsLampa;
    // End of variables declaration//GEN-END:variables
}
